# Generated by Django 4.0.9 on 2023-02-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=12)),
                ('type', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('time_in', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.vehicle')),
            ],
            options={
                'db_table': 'transaction_transaction',
            },
        ),
    ]
